export const HERO_TRUST_TEXT = {
  home: 'HELPING EASTERN PROVINCE BUSINESSES GROW ONLINE',
  ecommerce: 'HELPING EASTERN PROVINCE BUSINESSES SELL MORE ONLINE',
  fullStack: 'HELPING EASTERN PROVINCE BUSINESSES BUILD BETTER WEBSITES',
  seo: 'HELPING EASTERN PROVINCE BUSINESSES DOMINATE LOCAL SEARCH',
  aiSoftware: 'HELPING EASTERN PROVINCE BUSINESSES AUTOMATE WITH AI',
  software: 'HELPING EASTERN PROVINCE BUSINESSES RUN SMARTER SYSTEMS',
  about: 'HELPING EASTERN PROVINCE BUSINESSES TRANSFORM DIGITALLY',
  contact: 'HELPING EASTERN PROVINCE BUSINESSES GET FOUND & GROW',
};
